# Establishing Connections to Databases

In [ ]:
bridge_sfn =

## TIMS 'doticsqlp31' Data Source

In [1]:
import pandas as pd
import sqlalchemy as db
from sqlalchemy import create_engine, MetaData, text, inspect
from sqlalchemy.engine import URL

In [2]:
connection_string = (
    r"Driver=ODBC Driver 17 for SQL Server;"
    r"Server=doticsqlp31;"
    r"Database=TIMS;"
    r"Trusted_Connection=yes;"
)

connection_url = URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})

engine = create_engine(connection_url)
conn = engine.connect()

In [4]:
# Use Pandas to read the database, selects all but shape column
df = pd.DataFrame(
    conn.execute(
        text(
            "SELECT ObjectID, SFN, APPR_ROAD_ALIGNMENT, APPR_ROADWAY_WIDTH, NUMBER_OF_APPR_SPANS, APPR_KIND_MATERIAL_DESIGN, APPR_TYPE_DESIGN_CONSTRUCT, APPRH_STRUC_TYPE, BRIDGE_ROAD_WIDTH, BYPS_DETOUR_LENGTH, DECK_GEOMETRY, STRUCTL_EVALUATION, UNDERCLEAR_VERT_HORIZ, COUNTY_CD, CULVERTS, DECK_AREA, DECK_STRUCTURE_TYPE, TYPE_OF_MEMBRANE, DECK_PROTECTION, DECK_WIDTH_OUT_TO_OUT, DEFIC_FUNC_RATING, DESIGN_LOAD, DIRECTION_OF_TRAFFIC, ODOT_DISTRICT, FIPS, FUTURE_AVE_DAILY_TRAFFIC, FUTURE_AVG_DAILY_TRAF_YR, DIRECTIONAL_SUFFIX, FEATURES_INTERSECTED, ROUTE_DESIGNATION, SYSTEM_CD, HWY_SYS_OF_INVENT_RTE, ON_OR_UNDER, ROUTE_NUMBER, LANES_ON_STRUCTURE, LANES_UNDER_STRUCTURE, LATITUDE_DD_BEGIN, LONGITUDE_DD_BEGIN, SPANS_IN_MAIN_UNIT_NBR, KIND_OF_MATL_DESIGN, TYPE_OF_DESIGN_CONST, MAIN_STRUC_TYPE, MAINT_RESPONSIBILITY, YEAR_RECONSTRUCTED, LENGTH_OF_MAXIMUM_SPAN, BRIDGE_MEDIAN, INVENT_RTE_TOTL_HORZ_CLEAR, MIN_NAV_VERT_CLEAR_LIFT_BRG, INVENT_RTE_MIN_VERT_CLEAR, MIN_LAT_UNDERCLEAR_ON_LEFT, MIN_LAT_UNDERCLEAR_ON_RIGHT, NAVIGATION_CONTROL, NAVIGATION_HORIZ_CLEARANCE, NAVIGATION_VERTICAL_CLEARANCE, STRUCTURE_LENGTH, PAINT_DT, PARALLEL_STRUCT_DESIGNATION, MIN_VERT_CLEAR_OVER_BRG_RD, LEFT_CURB_SIDEWALK_WIDTH, RIGHT_CURB_SIDEWALK_WIDTH, SKEW, KILOMETER_POINT, LOCATION_TXT, FACILITY_CARRIED_BY_STRUCT, SUFF_RATING, TOLL, TYPE_OF_SERVICE_ON_BRG, TYPE_OF_SERVICE_UNDER_BRG, WEAR_SURF_DT, TYPE_OF_WEARING_SURFACE, WEARING_SURF_THCK, WATERWAY_ADEQUACY, PERCENT_RESPONSIBILITY, BORDER_BRG_STRUCT_NBR, NEIGHBORING_STATE_CODE, HISTORICAL_SIGNIFICANCE, STR_STEEL_PROT_CD, YEAR_BUILT, BRIDGE_IMPROVEMENT_COST, YEAR_OF_IMPROVE_COST_EST, LENGTH_OF_STRUCT_IMPROVE, ROADWAY_IMPROVEMENT_COST, TOTAL_PROJECT_COST, WORK_DONE_BY, TYPE_OF_WORK_PROPOSED, UNDERWATER_INSPECTION_DT, UNDERWATER_INSPECTION, DESIGNATED_INSPECTION_FREQ, FRACTURE_CRIT_DETAILS_DT, FRACTURE_CRITICAL_DETAILS, SCOUR_CRITICAL_BRIDGES, SNOOPER_BRIDGE_INSPECTION, OTHER_SPECIAL_INSPECT_DT, OTHER_SPECIAL_INSPECTION, CHANNEL_CHANNEL_PROTECTION, FLOOR_CONDITION_RATING, DECK, WEARING_SURF_CONDITION_RATING, GEN_APPR_CONDITION_RATING, STRUCT_OPEN_POSTED_CLOSED, INSPECTION_DATE, PCS_CONDITION_RATING, PIER_ABUTMENT_PROTECTION, SUBSTRUCTURE, SUPERSTRUCTURE, APPROACH_GUARDRAIL, APPROACH_GUARDRAIL_ENDS, BRIDGE_RAILINGS, TRANSITIONS, STRAHNET_HWY_DESIGNATION, DESIGN_NATIONAL_NETWORK, STRUCTURE_FLARED, MAJOR_BRG_SW, NBIS_BRIDGE_LENGTH, TEMP_STRUCT_DESIGNATION, AVERAGE_DAILY_TRAFFIC, YR_OF_AVE_DAILY_TRAFFIC, METH_TO_DETER_INVENT_RTE, INVENTORY_RATING, METH_TO_DETER_OPERTE_RTE, OPERATING_RATING, DATE_OPEN_TO_TRAFFIC, NLFID, CTL_BEGIN_NBR, LOAD_RAT_PCT, NBI_RATING, PRSRV_CANDIDATE, JURISDICTION, ROUTE_TYPE, DIVIDED_HWY, ACCESS_CONTROL, URBAN_AREA_CODE, BASE_TYPE, FUNCTIONAL_CLASS, HPMS_SAMPLE_ID, LANES, MAINTENANCE_AUTHORITY, NHS, PRIORITY_SYSTEM, SURFACE_TYPE, SURFACE_WIDTH, ESAL_TOTAL, PAVE_TYPE, PCR_YEAR, ROADWAY_WIDTH_NBR, created_user, created_date, last_edited_user, last_edited_date, GDB_GEOMATTR_DATA FROM TIMS.WGIS_BRIDGE"
        )
    )
)

In [5]:
df

,ObjectID,SFN,APPR_ROAD_ALIGNMENT,APPR_ROADWAY_WIDTH,NUMBER_OF_APPR_SPANS,APPR_KIND_MATERIAL_DESIGN,APPR_TYPE_DESIGN_CONSTRUCT,APPRH_STRUC_TYPE,BRIDGE_ROAD_WIDTH,BYPS_DETOUR_LENGTH,...,SURFACE_WIDTH,ESAL_TOTAL,PAVE_TYPE,PCR_YEAR,ROADWAY_WIDTH_NBR,created_user,created_date,last_edited_user,last_edited_date,GDB_GEOMATTR_DATA
0,67389232,0131997,7,21,0,0,00,000N,22.0,00,...,16.0,None,FLEX,None,20.0,TIMS@P31_AG,2021-10-22 07:18:19,TIMS@P31_AG,2021-10-22 07:18:19,None
1,67389233,0134002,7,22,0,0,00,000N,15.8,02,...,16.0,None,FLEX,None,20.0,TIMS@P31_AG,2021-10-22 07:18:19,TIMS@P31_AG,2021-10-22 07:18:19,None
2,67389234,0131970,7,16,0,0,00,000N,24.0,06,...,14.0,None,FLEX,None,18.0,TIMS@P31_AG,2021-10-22 07:18:19,TIMS@P31_AG,2021-10-22 07:18:19,None
3,67389235,0130169,7,24,0,0,00,000N,28.0,12,...,18.0,None,FLEX,None,22.0,TIMS@P31_AG,2021-10-22 07:18:19,TIMS@P31_AG,2021-10-22 07:18:19,None
4,67389236,0130192,5,18,0,0,00,000N,16.2,07,...,18.0,None,FLEX,None,22.0,TIMS@P31_AG,2021-10-22 07:18:19,TIMS@P31_AG,2021-10-22 07:18:19,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44980,67434212,2566095,8,26,0,0,00,000N,0.0,12,...,NaN,None,None,None,NaN,TIMS@P31_AG,2021-10-22 07:18:54,TIMS@P31_AG,2021-10-22 07:18:54,None
44981,67434213,2566370,8,39,0,0,00,000N,0.0,12,...,NaN,None,None,None,NaN,TIMS@P31_AG,2021-10-22 07:18:54,TIMS@P31_AG,2021-10-22 07:18:54,None
44982,67434214,2566141,8,26,0,0,00,000N,0.0,12,...,NaN,None,None,None,NaN,TIMS@P31_AG,2021-10-22 07:18:54,TIMS@P31_AG,2021-10-22 07:18:54,None
44983,67434215,2566206,8,32,0,0,00,000N,0.0,12,...,NaN,None,None,None,NaN,TIMS@P31_AG,2021-10-22 07:18:54,TIMS@P31_AG,2021-10-22 07:18:54,None
44984,67434216,2566044,8,26,0,0,00,000N,0.0,12,...,NaN,None,None,None,NaN,TIMS@P31_AG,2021-10-22 07:18:54,TIMS@P31_AG,2021-10-22 07:18:54,None

## 'DOTWarehousePrd' Data Source

In [7]:
connection_string = (
    r"Driver=SQL Server;"
    r"Server=DOTWarehousePrd;"
    r"Database=Warehouse;"
    r"Trusted_Connection=yes;"
)
connection_url = URL.create("mssql+pyodbc", query={"odbc_connect": connection_string})
engine = create_engine(connection_url)
conn = engine.connect()

In [8]:
# Get data from 1985-1990 table
hist85_90DataQuery = text("SELECT * from BMS_1985_1990")

In [9]:
hist_bridge_data = pd.read_sql(hist85_90DataQuery, conn)
hist_bridge_data

,Year_of_File,SFN,Jurisdiction,County_Code,Route,SLM,On_BARS,District,Inventory_On_Under,Inventory_Highway_System,...,Record_Add_Date,Blank,FHWA_Structure_Type,Dive_Inspection_Switch,Dive_Inspection_Frequency,Paint_Year,Sufficiency_Rating_,Culvert_Sufficiency_Default,Structurally_Deficient_Functionally_Obsolete,Bridge_Status_Code
0,1985,7130619,C,ROS,C 009,0797,0,09,1,4,...,19000101,,101,N,00,,078.4,2,,A
1,1985,7130635,C,ROS,C 009,0911,0,09,1,4,...,19000101,,101,N,00,,070.8,2,,A
2,1985,7134576,C,ROS,0C082,0183,0,09,1,4,...,19000101,,101,N,00,,083.4,0,,A
3,1985,7134959,C,ROS,0087C,0177,0,09,1,4,...,19000101,,101,N,00,,083.4,0,,A
4,1985,7135289,C,ROS,0087C,1080,0,09,1,4,...,19000101,,101,N,00,,074.3,0,,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254508,1990,5204410,S,MED,076R,0158,1,03,1,1,...,19000101,,402,N,00,1973,081.1,0,,A
254509,1990,5204445,S,MED,076R,0158,1,03,1,1,...,19000101,,402,N,00,1973,052.6,1,,A
254510,1990,7001088,S,RIC,030R,0978,0,03,2,2,...,19000101,,402,N,00,1981,070.3,0,,A
254511,1990,7707088,S,SUM,091R,0239,0,04,1,3,...,19000101,,303,N,00,1975,079.8,0,,A
254512,1990,7900155,S,TUS,036R,0091,1,11,1,2,...,19000101,,402,N,00,1983,079.4,2,,A